### ISSUE TITLE
请问这个的用法是？

### ISSUE THREAD

**Issue by wby238** [Odaimoko/Manga_DLer_CHN#1]
试着执行了一下，发现都是报paya模块错误……

**Comment by Odaimoko** [comment]
如果要下载漫画的话，已经有很全面的工具了.
[Comiccrawler](https://pypi.python.org/pypi/comiccrawler/2017.3.26)
我这里只是多了网易漫画的下载。

**Comment by Odaimoko** [comment]
如果真的是网易，然后想用的话，我现在还没有做接收输入的功能，所以得进代码改。paya/m.py里
	id_book = "4617223306170106339"
	ne_book = netease.NetEase_DLer(id_book)
	ne_book._dl()
默认下载于上一级目录，可以在const.py里面改。
注意这个会从第一话开始下载全部的内容。
使用的话，进paya文件夹，python m.py就可以。

**Comment by wby238** [comment]
@Odaimoko 就是为了下网易的……按照你说的改了，但还是报错。每个都试了下，报错信息如下：
```python
D:\Github\Manga_DLer_CHN-master\paya>basedler.py
Traceback (most recent call last):
  File "D:\Github\Manga_DLer_CHN-master\paya\basedler.py", line 2, in <
module>
    from paya.const import *
ImportError: No module named 'paya'

D:\Github\Manga_DLer_CHN-master\paya>const.py

D:\Github\Manga_DLer_CHN-master\paya>ikanman_manga.py
Traceback (most recent call last):
  File "D:\Github\Manga_DLer_CHN-master\paya\ikanman_manga.py", line 7,
 in <module>
    from paya import basedler
ImportError: No module named 'paya'

D:\Github\Manga_DLer_CHN-master\paya>m.py
Traceback (most recent call last):
  File "D:\Github\Manga_DLer_CHN-master\paya\m.py", line 10, in <module
>
    import paya.dl_manager as dl
ImportError: No module named 'paya.dl_manager'

D:\Github\Manga_DLer_CHN-master\paya>netease_manga.py
Traceback (most recent call last):
  File "D:\Github\Manga_DLer_CHN-master\paya\netease_manga.py", line 9,
 in <module>
    from paya import basedler
ImportError: No module named 'paya'
```

修改的代码如下：
```python
tcmjsnazhp = "4816503968880124552"#天才麻将少女阿知贺篇
ne_book = netease.NetEase_DLer(tcmjsnahzp)
ne_book._dl()
```

**Comment by Odaimoko** [comment]
一定要进paya文件夹里运行python，或者你用我在主文件夹下给的.bat也行。
**E:\_\D\Py\Manga_DLer_CHN\paya>**_python m.py_
```
['book-title="天才麻将少女" h5Domain']
开始下载篇章 ../天才麻将少女_163_/
开始下载 ../天才麻将少女_163_/0001 第1话 邂逅/ 共 33 页
../天才麻将少女_163_/0001 第1话 邂逅 created.
开始下载 ../天才麻将少女_163_/0002 第2话 再战/ 共 33 页
../天才麻将少女_163_/0002 第2话 再战 created.
开始下载 ../天才麻将少女_163_/0003 第3话 对决/ 共 35 页
../天才麻将少女_163_/0003 第3话 对决 created.
```

我修了一下，你重新下一个现在试试？
应该是没问题的，因为之前我已经把天麻和阿知贺都下下来又看了一遍。

**Comment by wby238** [comment]
现在能用了，thx
请问一下有出错自动重试的功能吗？刚刚在下载过程中出错了：
```
开始下载 ../天才麻将少女_163_/0018 第15局 开眼/ 共 34 页
../天才麻将少女_163_/0018 第15局 开眼 created.
('错误', IncompleteRead(196216 bytes read, 13759 more expected))
Shippai This Folder: ../天才麻将少女_163_/0018 第15局 开眼/ , pic No: 18  , URL:
  https://nos.netease.com/comic/579ec3cf366743608dc6dad6ca927a61?NOSAccessKeyId=
c92f74b0d48f4fb39271a1109da74cc2&Expires=1491059546&Signature=MAHK%2BkNGAlyJtTrG
VxkW0F0A4aG1d8EhJ9aaREzhVTw%3D
```

**Comment by wby238** [comment]
@Odaimoko 顺便提一下，下载的图片的真实格式应该是jpg而不是png的……

**Comment by Odaimoko** [comment]
改错的话，因为网易错误比较少，所以没有加，不过重新运行一次m.py就好了，因为有记录下载话。
确实是jpg的，不过读图软件都是按照文件本身的二进制内容来确定格式读取的，所以后缀名应该无所谓。

**Comment by wby238** [comment]
运行过程中时常会出现下面的错误，然后直接退出了，触发与否全靠运气，这是bug吗？
```python
开始下载 ../钢之炼金术师_163_/0050 第46话 遥远的背影/ 共 51 页
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\http\client.py", line 541, in _get_chunk_l
eft
    chunk_left = self._read_next_chunk_size()
  File "C:\Program Files\Python35\lib\http\client.py", line 508, in _read_next_c
hunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\http\client.py", line 558, in _readall_chu
nked
    chunk_left = self._get_chunk_left()
  File "C:\Program Files\Python35\lib\http\client.py", line 543, in _get_chunk_l
eft
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "m.py", line 99, in <module>
    ne_book._dl()
  File "..\paya\basedler.py", line 142, in _dl
    self.dl_whole_book()
  File "..\paya\netease_manga.py", line 305, in dl_whole_book
    self.dl_ep(pages, url_one_wa, ep_folder_name)
  File "..\paya\netease_manga.py", line 235, in dl_ep
    str_con = response.read().decode("utf8")
  File "C:\Program Files\Python35\lib\http\client.py", line 455, in read
    return self._readall_chunked()
  File "C:\Program Files\Python35\lib\http\client.py", line 565, in _readall_chu
nked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(51008 bytes read)
```

**Comment by wby238** [comment]
@Odaimoko 居然遇到了bug，但这bug……我无话可说……
```python
../斗罗大陆3龙王传说_163_/0037 37 初遇好基友？！约吗？约！01/010.png 已下载
开始下载 ../斗罗大陆3龙王传说_163_/0038 38 初遇好基友?!约吗?约!02/ 共 10 页
Traceback (most recent call last):
  File "m.py", line 111, in <module>
    ne_book._dl()
  File "..\paya\basedler.py", line 142, in _dl
    self.dl_whole_book()
  File "..\paya\netease_manga.py", line 305, in dl_whole_book
    self.dl_ep(pages, url_one_wa, ep_folder_name)
  File "..\paya\netease_manga.py", line 232, in dl_ep
    createFolder(folder_name, self.log_file_name)
  File "..\paya\const.py", line 87, in createFolder
    os.makedirs(name)
  File "C:\Program Files\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '../斗罗大陆3龙王传说_
163_/0038 38 初遇好基友?!约吗?约!02'
```

**Comment by Odaimoko** [comment]
第一个，估计是网络问题，我以前也没遇见过，暂且还不知道除了重试以外的方法。
第二个已经修复。
如果有其他问题，还是新开issue比较好。

**Comment by wby238** [comment]
OK,thx
