### ISSUE TITLE
替换字符的函数出错了吧？

### ISSUE THREAD

**Issue by wby238** [Odaimoko/Manga_DLer_CHN#2]
刚刚看了更新，我没记错的话，","（逗号）是可以用于文件名的，那个替换应该是半角冒号":"到全角冒号的吧？
```python
def safe_file_name(s):
 	if s==None:
 		return None
 	return s.replace("/", "／").replace("\\", "＼").replace("?", "？").\
 		replace("|", "｜").replace("<", "＜").replace(">", "＞").\
 		replace(",", "：").replace("\"", "＂").replace("*", "＊")
```

**Comment by wby238** [comment]
刚刚看的还不是最新的，没事了……

**Comment by wby238** [comment]
居然又撞上了bug……
编号：4317018722750061499，名字为“新♠杀手古德”，文件夹倒是成功创建了，但无法下载，虽然下面报GBK无法编码特殊符号。
试着转换了下，'\u2660'为'♠'。
```python
开始下载篇章 Traceback (most recent call last):
  File "m.py", line 114, in <module>
    ne_book._dl()
  File "D:\2017编程\Github\Manga_DLer_CHN-master\paya\basedler.py", line 142, in
 _dl
    self.dl_whole_book()
  File "D:\2017编程\Github\Manga_DLer_CHN-master\paya\netease_manga.py", line 29
4, in dl_whole_book
    record_log(self.log_file_name, "开始下载篇章", chap_foldername)
  File "D:\2017编程\Github\Manga_DLer_CHN-master\paya\const.py", line 65, in rec
ord_log
    print(*src)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2660' in position 4: i
llegal multibyte sequence
```

**Comment by Odaimoko** [comment]
已修正，这个原因是print默认的编码是gbk，加一句把stdout改成utf8了。
顺带我这里并没有遇到这个问题= =
